[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA"
linker = "flip-link"

[build]
target = "thumbv7em-none-eabihf"
# thumbv7em-none-eabihf is good for nrf52840 (nice!nano) and STM32F411CEU6 (black-pill)
# thumbv7m-none-eabi is good for STM32F103C8T6 (blue-pill)
# thumbv6m-none-eabi is good for rp2040

[env]
DEFMT_LOG = "info"
